version = 0.1
[default.deploy.parameters]
stack_name = "dataspan-v1"
resolve_s3 = true
s3_prefix = "dataspan-v1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "NumOfConcurrentJobs=\"5\""
image_repositories = []
