AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template to create a Lambda function, EventBridge event bus, and SNS topic.

Parameters:
  NumOfConcurrentJobs:
    Type: Number
    Description: The number of concurrent executions for the Lambda function.
    Default: 5
    MinValue: 1 

Resources:
  MyEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: MyEventBus

  JobLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_service.service_handler
      Runtime: python3.9
      CodeUri: lambda_service/
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
          ASYNC_JOB_FUNC_NAME: !GetAtt DelayLambdaFunction.Arn
      Events:
        DelayHandler:
          Type: Api 
          Properties:
            Path: /dataspan/delay
            Method: post
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !GetAtt DelayLambdaFunction.Arn

  DelayLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_async_job_runner.lambda_handler
      Runtime: python3.9
      CodeUri: lambda_async_job_runner/
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref MyEventBus
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - events:PutEvents
            Resource: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${MyEventBus}

  JobListenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_job_listener.job_listener_handler
      Runtime: python3.9
      CodeUri: lambda_job_listener/
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
          SNS_TOPIC_ARN: !Ref SnsTopic
      Events:
        EventBusRule:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref MyEventBus
            Pattern:
              source:
                - "my.custom.source"
              detail-type:
                - "LambdaFunctionCompleted"
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - "dynamodb:UpdateItem"
            Resource: !GetAtt DynamoDBTable.Arn
        - Statement:
            Effect: Allow
            Action:
              - "sns:Publish"
            Resource: !Ref SnsTopic

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DataspanDynamoDBTable
      AttributeDefinitions:
        - AttributeName: IdParam
          AttributeType: S
        - AttributeName: JobStatus
          AttributeType: S
      KeySchema:
        - AttributeName: IdParam
          KeyType: HASH
        - AttributeName: JobStatus
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MySnsTopic

Outputs:
  EventBusName:
    Description: Event bus name
    Value: !Ref MyEventBus

  JobLambdaFunctionName:
    Description: Job Lambda function name
    Value: !Ref JobLambdaFunction

  DelayLambdaFunctionName:
    Description: Delay Lambda function name
    Value: !Ref DelayLambdaFunction

  JobListenerFunctionName:
    Description: Job Listener Lambda function name
    Value: !Ref JobListenerFunction

  SnsTopicArn:
    Description: SNS topic ARN
    Value: !Ref SnsTopic

  ApiUrl:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/dataspan/delay"
